refactor root index.js file
Jears017/star-wars-application pull request #6
Opened 2022-03-02 11:46 UTC by Jears017

2022-03-02 14:09 UTC, BLRplex requested changes

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +            sx={{ mr: 2, display: { xs: "none", md: "flex" } }}
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +          <Box sx={{ flexGrow: 1, display: { xs: "flex", md: "none" } }}>
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +                display: { xs: "block", md: "none" },
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +                    style={{ textDecoration: "none", color: "white" }}
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +            sx={{ flexGrow: 1, display: { xs: "flex", md: "none" } }}
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +          <Box sx={{ flexGrow: 1, display: { xs: "none", md: "flex" } }}>
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +                  sx={{ my: 2, color: "white", display: "block" }}
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +                style={{ textDecoration: "none" }}
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +          <Box sx={{ flexGrow: 0 }}>
Стили через makeStyles

2022-03-02 14:09 UTC, BLRplex commented on src/index.js
> +import App from "./App";
Где разделение блоков?

2022-03-02 14:09 UTC, BLRplex commented on src/index.js
> +const theme = createTheme({
Говорил, что тему надо вынести в отдельный файл

2022-03-03 08:55 UTC, BLRplex requested changes

2022-03-03 08:55 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +} from "@mui/material";
Разделяй такие группы пустой строкой, чтобы визуально не слипалось в стены кода

2022-03-03 08:55 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +    navBarItem: { my: 2, color: "white", display: "block" },
Все цвета в тему

2022-03-03 08:55 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +    navBarItem: { my: 2, color: "white", display: "block" },
То есть, в теме их определяешь, в стилях загружаешь из темы

2022-03-03 08:55 UTC, BLRplex commented on src/App.jsx
>  import React from "react";
Примени конфиг линта, который я скидывал вчера

2022-03-03 08:58 UTC, Jears017 commented on src/App.jsx
>  import React from "react";
@BLRplex я же использую тот конфиг который ты скинул, не понимаю, что не так?

2022-03-03 11:04 UTC, BLRplex requested changes

2022-03-03 11:04 UTC, BLRplex commented on src/App.jsx
> +import { Header } from './components/blocks/Header'
Группы импортов должны разделяться, посмотри пожалуйста стайлгайд еще раз и внимательно, каждый раз на это буду указывать

2022-03-03 11:04 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +import {
Где визуальное разделение?

2022-03-03 11:04 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +import { makeStyles, createStyles } from '@mui/styles'
Где визуальное разделение?

2022-03-03 11:04 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +    navBarItem: { my: 2, color: 'white', display: 'block' },
Почему цвета не берутся из темы?

2022-03-03 11:04 UTC, BLRplex commented on src/components/blocks/Header.jsx
> +    navLink: { textDecoration: 'none', color: 'white' },
Почему цвета не берутся из темы?

2022-03-03 13:15 UTC, BLRplex requested changes

2022-03-03 13:15 UTC, BLRplex commented on .eslintrc
> +  //"parser": "babel-eslint",
Это как? Комментарии? В JSON?

2022-03-03 13:15 UTC, BLRplex commented on src/theme/theme.js
> +      main: '#000000',
Черный и белый, обычно иначе именуют. Например:
theme.palette.common.white
theme.palette.common.dark

Цвета primary и secondary - это чуть другое. Если ты откроешь, например, вконтакт, то там примари будет синий цвет

2022-03-03 13:47 UTC, BLRplex approved these changes

2022-03-03 14:10 UTC, merged